apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: bamboo build
description: A composite for bamboo build actions
inputs:
  url:
    description: 'bamboo url'
    required: true
  username:
    description: 'bamboo user name'
    required: true
  password:
    description: 'bamboo password'
    required: true
  project-name:
    description: 'bamboo project name'
    required: false    
  plan-name:
    description: 'bamboo plan name'
    required: false
    default: ''
  branch-name:
    description: 'bamboo branch name'
    required: false
    default: ''      
  deploy-project-name: 
    description: 'bamboo deploy project id'
    required: false
  release-name: 
    description: 'bamboo release name'
    required: false    
  env-name:
    description: 'bamboo env name'
    required: false    
  invoke-type:
    description: 'tool type'
    required: false
  test-type:
    description: 'test type'
    required: false
    default: ''
  test-result-location: 
    description: 'test result location'
    required: false
    default: ''



runs:
  using: composite
  steps:
    - id: run-bamboo-action
      name: run-bamboo-action
      uses: docker://public.ecr.aws/l7o7z1g8/actions/bamboo-actions:main-ca584a59add9e9251f0b5ec2b81846573af62ebc
      shell: sh
      env:        
        CONFIG_JSON: '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"${{ inputs.invoke-type }}","username":"${{ inputs.username }}","password":"${{ inputs.password }}","projectName":"${{ inputs.project-name }}","planName":"${{ inputs.plan-name }}","branchName":"${{ inputs.branch-name }}","deployProjectName":"${{ inputs.deploy-project-name }}","releaseName":"${{ inputs.release-name }}","testType":"${{ inputs.test-type }}","fileName":"${{ inputs.test-result-location }}"},"envVariables":{"env-name":"${{ inputs.env-name }}"}}'   
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }} 
      run: |
        
        set -x
        cd /app
        ./bamboo_actions_app invoke -i $CONFIG_JSON
        
